from tkinter import ttk
class constants:
    BLUE_TARDIS = "#003B6F"
    TEAL_VORTEX_GLOW = "#00B8C6"
    GOLD_GALLIFREYAN = "#FFD700"
    CHARCOAL_SONIC_SHADOW = "#1C1C1E"
    PURPLE_NEBULA = "#6E44FF"
    SILVER_TIME_MIST = "#D3D9DE"
    PINK_COMPANION_ROSE = "#E75A7C"
    BRONZE_DALEK = "#8C6E52"
